FROM node:14.15.0 as build

WORKDIR /frontend

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

# production environment
FROM nginx:1.19.10-alpine
COPY --from=build /app/build /usr/share/nginx/html

COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]