services:
  api:
    build: ./backend        
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py migrate; python manage.py loaddata fixtures/users.json; python manage.py loaddata fixtures/products.json; python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
        - "5432:5432"
    

  web:
    build: ./frontend
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - api


volumes:
  postgres_data: